<a href="https://colab.research.google.com/github/girish342/fastai-v3/blob/master/Activation_relu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# activation means to activate neural network 
# relu = rectified linear unit
# we use relu because it fits great into non linear data 
# it converts output to either 0 or max in postive integers 

In [3]:
!pip install nnfs

In [0]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data


In [0]:
nnfs.init()
X = [[1,2,3,4],
     [0.5,2.5,3.5,1.5],
     [3,4,2,1]]  

In [0]:
X,y = spiral_data(100,3)

In [0]:
np.random.seed(0)
class Layer_Dense:
  def __init__(self,n_inputs,n_neurons ):
      self.weights = 0.10 * np.random.randn(n_inputs,n_neurons)  # it gives rise to shape of matrix of weights 
      self.biases = np.zeros((1,n_neurons))
  def forward(self,inputs):
      self.output = np.dot(inputs, self.weights) + self.biases 



class Activation_ReLU:
  def forward(self,inputs):
    self.output = np.maximum(0,inputs)

In [11]:
layer1 = Layer_Dense(2,5)  # 4=inputs,5=neurons
activation1 = Activation_ReLU()
layer1.forward(X)
#print(layer1.output)
activation1.forward(layer1.output)
print(activation1.output)


[[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [1.9723912e-04 1.3000938e-03 8.9394738e-04 0.0000000e+00 0.0000000e+00]
 [4.4291088e-04 2.4017927e-03 7.2769134e-04 0.0000000e+00 0.0000000e+00]
 ...
 [0.0000000e+00 0.0000000e+00 1.1289997e-01 1.7913374e-01 2.5910899e-02]
 [0.0000000e+00 0.0000000e+00 6.9648728e-02 1.9956945e-01 3.8423590e-02]
 [0.0000000e+00 5.3640064e-03 1.2378567e-01 1.7383415e-01 2.2722276e-02]]
